services:
  - type: web
    name: flowshare-backend
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: CORS_ORIGIN
        value: https://Dheeraj2209.github.io
      - key: DATA_DIR
        value: /var/data
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
